spring:
  datasource:
    url: jdbc:mysql://localhost/project_volunteer?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
security:
  roles:
    - id: 1
      role: "ROLE_VOLUNTEER"
    - id: 2
      role: "ROLE_INDIVIDUAL"
    - id: 3
      role: "ROLE_COMPANY"
  minIdSum: 1
  maxIdSum: 3