spring:
  datasource:
    url: jdbc:mysql://localhost/project_volunteer?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
security:
  roles:
    - id: 1
      role: "ROLE_VOLUNTEER"
    - id: 2
      role: "ROLE_INDIVIDUAL"
    - id: 3
      role: "ROLE_COMPANY"
  minIdSum: 1
  maxIdSum: 3
errorMessages:
  wrongRoles: "BAD_REQUEST: Roles are not set correctly"
  usernameNotFound: "BAD_REQUEST: Username doesn't exist"