spring:
  datasource:
    url: jdbc:mysql://localhost/project_volunteer?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: scrummybears08@gmail.com
    password: ScrumProject0821!#
    transport.protocol: smtp
    smtp:
      auth: true
      starttls.enable: true
    debug: true


message:
  subject: Incorrect password for 5 times
  text: Was this you? Someone tried to login with an incorrect password for 5 times. Please reset your Password.
  pathToAttachment: project_volunteer/src/main/resources/Scrummy Bears Logo.jpg

  #https://drive.google.com/file/d/1_0k1HyesHZC1R6oEZ2q3MY5FiaMhKPie/view?usp=sharing

roles:
  roleVolunteer:
    role: "ROLE_VOLUNTEER"
  roleIndividual:
    role: "ROLE_INDIVIDUAL"
  roleCompany:
    role: "ROLE_COMPANY"

